AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  FullRepositoryId:
    Type: String
    Description: GitHub repository in the format owner/repo.

  BranchName:
    Type: String
    Default: main
    Description: The branch to use for the pipeline source.

  DevOU:
    Type: String
    Description: The OU for the dev environment.

  TestOU:
    Type: String
    Description: The OU for the test environment.

  ProdOU:
    Type: String
    Description: The OU for the prodv environment.

  TargetRoleName:
    Type: String
    Default: cfn-deploy
    Description: Name of the role in the target accounts

  PipelineName:
    Type: String
    Description: The name of the CodePipeline.

  Region:
    Type: String
    Default: us-east-1
    Description: The AWS Region/s where the templates will be deplyed.

  TemplatesPath:
    Type: String
    Description: Path for the CloudFormation templates

  ParametersPath:
    Type: String
    Description: Path for the CloudFormation parameters files


Resources:

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RoleArn: !Sub "{{resolve:ssm:/iam/codepipeline-role-arn}}"

      ArtifactStore:
        Type: S3
        Location: !Sub "{{resolve:ssm:/s3/artifact-bucket-name}}"
        EncryptionKey:
          Id: !Sub "{{resolve:ssm:/kms/artifact-key-arn}}"
          Type: KMS

      Stages:
        # Fetches the source code from GitHub via CodeStar Connections.
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !Sub "{{resolve:ssm:/codepipeline/github-connection-arn}}"
                FullRepositoryId: !Ref FullRepositoryId
                BranchName: !Ref BranchName
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceOut

        #Deploy Infra Resources
        - Name: Deploy-app-infra
          Actions:

            - Name: deploy-security-groups
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormationStackSet
                Version: "1"
              InputArtifacts:
                - Name: SourceOut
              Configuration:
                PermissionModel: SERVICE_MANAGED
                CallAs: DELEGATED_ADMIN
                StackSetName: deploy-security-groups
                MaxConcurrentPercentage: "50"
                FailureTolerancePercentage: "100"
                ConcurrencyMode: SOFT_FAILURE_TOLERANCE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                DeploymentTargets: !Ref DevOU
                TemplatePath: !Sub "SourceOut::${TemplatesPath}/security_groups.yaml"
                Parameters: !Sub "SourceOut::${ParametersPath}/security_groups.json"
                Regions: !Ref Region
              RunOrder: 1

            - Name: deploy-ec2
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormationStackSet
                Version: "1"
              InputArtifacts:
                - Name: SourceOut
              Configuration:
                PermissionModel: SERVICE_MANAGED
                CallAs: DELEGATED_ADMIN
                StackSetName: deploy-ec2
                MaxConcurrentPercentage: "50"
                FailureTolerancePercentage: "100"
                ConcurrencyMode: SOFT_FAILURE_TOLERANCE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                DeploymentTargets: !Ref DevOU
                TemplatePath: !Sub "SourceOut::${TemplatesPath}/ec2.yaml"
                Parameters: !Sub "SourceOut::${ParametersPath}/ec2.json"
                Regions: !Ref Region
              RunOrder: 2


            - Name: deploy-rds
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormationStackSet
                Version: "1"
              InputArtifacts:
                - Name: SourceOut
              Configuration:
                PermissionModel: SERVICE_MANAGED
                CallAs: DELEGATED_ADMIN
                StackSetName: deploy-rds
                MaxConcurrentPercentage: "50"
                FailureTolerancePercentage: "100"
                ConcurrencyMode: SOFT_FAILURE_TOLERANCE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                DeploymentTargets: !Ref DevOU
                TemplatePath: !Sub "SourceOut::${TemplatesPath}/rds.yaml"
                Parameters: !Sub "SourceOut::${ParametersPath}/rds.json"
                Regions: !Ref Region
              RunOrder: 3