AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 bucket

Parameters:
  AppName:
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '{{resolve:ssm:/params/env_name}}-${AppName}'
      VersioningConfiguration:
        Status: Enabled

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyDeleteWithoutMFA
            Effect: Deny
            Principal: "*"
            Action:
              - s3:DeleteObject
              - s3:DeleteObjectVersion
            Resource: !Sub "arn:aws:s3:::${Bucket}/*"
            Condition:
              BoolIfExists:
                aws:MultiFactorAuthPresent: "false"
                aws:ViaAWSService: "false"

  BucketArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/s3/${AppName}-bucket/arn'
      Value: !GetAtt Bucket.Arn
      Type: String