AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DBPort:
    Type: Number
    Description: Database port
  AppName:
    Type: String

Resources:
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Bastion Security Group
      VpcId: "{{resolve:ssm:/net/vpc/id}}"
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-bastion-sg"

  AppEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 App Security Group
      VpcId: "{{resolve:ssm:/net/vpc/id}}"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: "SSH from anywhere (temporary for GitHub Actions)"
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-ec2-sg"

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DB Security Group
      VpcId: "{{resolve:ssm:/net/vpc/id}}"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref DBPort
          ToPort: !Ref DBPort
          SourceSecurityGroupId: !Ref AppEC2SecurityGroup
        - IpProtocol: tcp
          FromPort: !Ref DBPort
          ToPort: !Ref DBPort
          SourceSecurityGroupId: !Ref BastionSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-db-sg"

  LBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow HTTP and HTTPS for Load Balancer"
      VpcId: "{{resolve:ssm:/net/vpc/id}}"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-lb-sg"

  BastionSGIDParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ec2/securitygroups/bastion-sg/id
      Value: !GetAtt BastionSecurityGroup.GroupId
      Type: String

  AppEC2SGIDParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ec2/securitygroups/app-ec2-sg/id
      Value: !GetAtt AppEC2SecurityGroup.GroupId
      Type: String

  DBSGIDParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ec2/securitygroups/db-sg/id
      Value: !GetAtt DBSecurityGroup.GroupId
      Type: String

  LBSGIDParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ec2/securitygroups/lb-sg/id
      Value: !GetAtt LBSecurityGroup.GroupId
      Type: String