AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DBPort:
    Type: Number
    Description: Database port
  AppName:
    Type: String

Resources:

  EC2AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 App Security Group
      VpcId: "{{resolve:ssm:/net/vpc/id}}"
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-ec2-sg"

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DB Security Group
      VpcId: "{{resolve:ssm:/net/vpc/id}}"
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-db-sg"

  EC2ToDbIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DBSecurityGroup
      IpProtocol: tcp
      FromPort: !Ref DBPort
      ToPort: !Ref DBPort
      SourceSecurityGroupId: !Ref EC2AppSecurityGroup 
          
  EC2SGIDParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ec2/securitygroups/ec2-sg/id
      Value: !GetAtt EC2AppSecurityGroup.GroupId
      Type: String

  DBSGIDParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ec2/securitygroups/db-sg/id
      Value: !GetAtt DBSecurityGroup.GroupId
      Type: String