AWSTemplateFormatVersion: '2010-09-09'
Description: Creates KMS CMK Key in the Management Account

Parameters:
  OrgId:
    Type: String
    Description: Your AWS Organizations ID

Resources:
  KmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Central Backups
      EnableKeyRotation: true
      MultiRegion: True
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: RootAdmin
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"

          - Sid: AllowServiceForOrg
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:CreateGrant
              - kms:Encrypt
              - kms:Decrypt 
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
              - kms:GetKeyPolicy 
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
              - kms:ReplicateKey
            Resource: "*"
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref OrgId

  KeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/central-backup
      TargetKeyId: !Ref KmsKey
