AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvName:
    Type: String

Resources:

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group
      VpcId: !Sub '{{resolve:ssm:/net/${EnvName}-vpc/id}}'
      Tags:
        - Key: Name
          Value: ec2-sg
          
  SGIDParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ec2/securitygroups/ec2-sg/id
      Value: !GetAtt EC2SecurityGroup.GroupId
      Type: String