AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation template to create an Amazon Aurora PostgreSQL Serverless v2 cluster
  with automatic scaling capabilities. 

Mappings:
  AccountIDToEnvironment:
    "410859982962": # Replace with your actual Dev Account ID
      Environment: "dev"
    "109648734102": # Replace with your actual Prod Account ID
      Environment: "test"
    "981425614813": # Replace with your actual QA Account ID
      Environment: "prod"

Outputs:
  EnvironmentName:
    Description: The environment name based on the AWS Account ID.
    Value:
      !FindInMap
        - AccountIDToEnvironment # The name of the Mapping
        - !Ref "AWS::AccountId"   # The key to search (the Account ID)
        - Environment             # The key for the value to retrieve

Resources:

  DBMasterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/rds/${EnvironmentName}-db/master"
      GenerateSecretString:
        # Template ensures the secret structure is compatible with RDS
        SecretStringTemplate: !Sub '{"username": "${DBMasterUsername}", "engine": "postgres"}'
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
        RequireEachIncludedType: true

  # 2. DB Subnet Group: Defines the subnets the cluster can use
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for Aurora Serverless V2
      SubnetIds: !Ref SubnetIds

  # 3. Security Group: Allows internal traffic on PostgreSQL port (5432)
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the Aurora PostgreSQL Cluster
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        # Self-referencing rule to allow all components in this group to talk to each other
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref DBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${DBClusterIdentifier}-SG"

  # 4. Aurora DB Cluster: The main database resource
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: !Ref PostgresEngineVersion
      DBClusterIdentifier: !Ref DBClusterIdentifier
      # *** KEY CHANGE: Using Secrets Manager for credentials ***
      # Replaces MasterUsername and MasterUserPassword
      MasterUserSecret:
        SecretArn: !Ref DBMasterSecret
      
      DatabaseName: maindb
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !GetAtt DBSecurityGroup.GroupId
      
      # *** KEY FOR SERVERLESS V2 ***
      ServerlessV2ScalingConfiguration:
        MinCapacity: !Ref DBMinACUCapacity
        MaxCapacity: !Ref DBMaxACUCapacity
        
      BackupRetentionPeriod: 7
      StorageEncrypted: true
      DeletionProtection: false # Set to true for production environments
      
  # 5. Aurora DB Instance: The required writer instance for the cluster
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      # *** KEY FOR SERVERLESS V2 ***
      DBInstanceClass: db.serverless 
      Engine: aurora-postgresql
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub "${DBClusterIdentifier}-instance"

Outputs:
  DBClusterEndpoint:
    Description: The Endpoint URL for the Aurora Cluster
    Value: !GetAtt DBCluster.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-ClusterEndpoint"

  DBClusterPort:
    Description: The Port for the Aurora Cluster
    Value: !GetAtt DBCluster.Endpoint.Port
    Export:
      Name: !Sub "${AWS::StackName}-ClusterPort"

  DBSecurityGroupId:
    Description: Security Group ID for the DB Cluster
    Value: !GetAtt DBSecurityGroup.GroupId
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroupId"
  
  MasterSecretARN:
    Description: ARN of the Secrets Manager secret containing master credentials
    Value: !Ref DBMasterSecret
    Export:
      Name: !Sub "${AWS::StackName}-MasterSecretARN"
